tproxy-port: 0
redir-port: 9454
mode: rule
allow-lan: true
unified-delay: true
bind-address: '*'
log-level: error
ipv6: true
geodata-mode: true
external-controller: 0.0.0.0:9090
external-ui: dashboard/dist
tcp-concurrent: false
# interface-name: ""
enable-process: true
geodata-loader: memconservative
# routing-mark: 233
inbound-tfo: false
secret: ""
# geox-url: {mmdb: "", geoip: "", geosite: ""}
profile:
  store-selected: true
  store-fake-ip: false
experimental: {sniff-tls-sni: true, fingerprint: ""}
sniffer:
  enable: true
  sniffing: [tls, http]
  force-domain:
    - '+'
  skip-domain:
    - '+.google.com'
  port-whitelist: [443, 80]
  force-dns-mapping: true
  parse-pure-ip: true
hosts: {"cacerts.digicert.com": "104.21.21.147", "ota.googlezip.net": "127.0.0.1", "ota-cache1.googlezip.net": "127.0.0.1", "ota-cache2.googlezip.net": "127.0.0.1"}
tun:
  enable: true
  device: tun0
  stack: system
  mtu: 9000
  dns-hijack:
    - any:53
  auto-route: true
  auto-detect-interface: true
  strict_route: false
  inet4_address: 198.18.0.1/16
  inet6_address: [fdfe:dcba:9876::1/126]
dns:
  enable: true
  ipv6: false
  prefer-h3: false
  default-nameserver:
    - 'tcp://1.0.0.1' # Cloudflare
  listen: 0.0.0.0:1053
  use-hosts: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter: ["*.local", "*.localhost"]
  nameserver:
    - 'https://1.1.1.1/dns-query' # Cloudflare
    - 'https://8.8.8.8/dns-query' # Google
  proxy-server-nameserver:
    - 'https://dns.google/dns-query'
  fallback: []
  fallback-filter:
    geoip: false
    geoip-code: "ID"
    geosite: []
    ipcidr: [0.0.0.0/8, 10.0.0.0/8]
    domain: ['+.google.com', '+.youtube.com']
proxies:
rule-providers:
  Direct:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/wikann/Rule/main/Direct.yaml
    path: "./rule_provider/direct.yaml"
    interval: 100
  ADS:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/wikann/Rule/main/Ads.yaml
    path: "./rule_provider/ads.yaml"
    interval: 100
  Reject:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/wikann/Rule/main/Reject.yaml
    path: "./rule_provider/reject.yaml"
    interval: 100
  Instagram:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/wikann/Rule/main/Instagram.yaml
    path: "./rule_provider/ig.yaml"
    interval: 100
  Facebook:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/wikann/Rule/main/Facebook.yaml
    path: "./rule_provider/fb.yaml"
    interval: 100
  Twitter:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/wikann/Rule/main/Twitter.yaml
    path: "./rule_provider/tw.yaml"
    interval: 100
  Whatsapp:
    type: http
    behavior: domain
    url : https://raw.githubusercontent.com/wikann/Rule/main/Whatsapp.yaml
    path: "./rule_provider/Whatsapp.yaml"
    interval: 100
  YouTube:
    type: http
    behavior: domain
    path: "./rule_provider/Youtube.yaml"
    url: https://raw.githubusercontent.com/wikann/Rule/main/Youtube.yaml
    interval: 100
  Speedtest:
    type: http
    behavior: domain
    path: "./rule_provider/Speedtest.yaml"
    url: https://raw.githubusercontent.com/wikann/Rule/main/Speedtest.yaml
    interval: 100
  18+:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/wikann/Rule/main/Porn.yaml
    path: "./rule_provider/porn.yaml"
    interval: 100
  Streaming:
    type: file
    behavior: classical
    path: "./rule_provider/streaming.yaml"
    interval: 100
  Telegram:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/wikann/Rule/main/Telegram.yaml
    path: "./rule_provider/telegram.yaml"
    interval: 100
proxy-providers:
  "ID":
    type: http
    path: "./confs/ID.yaml"
    url: https://raw.githubusercontent.com/wikann/Akun/main/ID.yaml?token=GHSAT0AAAAAAB3UYKPKPHARU656HMIXJ62CY4CFKEQ
    health-check:
      enable: true
      url: http://cp.cloudflare.com/generate_204
      interval: 300
  "SG":
    type: http
    path: "./confs/SG.yaml"
    url: https://raw.githubusercontent.com/wikann/Akun/main/SG.yaml?token=GHSAT0AAAAAAB3UYKPKTTUNHTWP7QGDIWQGY4CFKZQ
    health-check:
      enable: true
      url: http://cp.cloudflare.com/generate_204
      interval: 300
proxy-groups:
- name: PRANA
  type: select
  use:
  - "ID"
  - "SG"
  proxies:
  - "PING"
  - "LB ID"
  - "LB SG"

- name: "LB ID"
  type: load-balance
  strategy: round-robin
  disable-udp: false
  use:
  - "ID"
- name: "LB SG"
  type: load-balance
  strategy: round-robin
  disable-udp: false
  use:
  - "SG"
  url: http://www.gstatic.com/generate_204
  interval: '300'
- name: "PING"
  type: url-test
  disable-udp: false
  use:
  - "ID"
  - "SG"
  url: http://cp.cloudflare.com/generate_204
  interval: '300'
  tolerance: '150'
- name: Instagram
  type: select
  use:
  - "ID"
  - "SG"
  proxies:
  - PRANA
  - DIRECT
  - REJECT
  - "PING"
  - "LB SG"
  - "LB ID"
- name: Facebook
  type: select
  use:
  - "ID"
  - "SG"
  proxies:
  - PRANA
  - DIRECT
  - REJECT
  - "PING"
  - "LB SG"
  - "LB ID"
- name: Twitter
  type: select
  use:
  - "ID"
  - "SG"
  proxies:
  - PRANA
  - DIRECT
  - REJECT
  - "PING"
  - "LB SG"
  - "LB ID"
- name: Telegram
  type: select
  use:
  - "ID"
  - "SG"
  proxies:
  - PRANA
  - DIRECT
  - REJECT
  - "PING"
  - "LB SG"
  - "LB ID"
- name: Whatsapp
  type: select
  use:
  - "ID"
  - "SG"
  proxies:
  - PRANA
  - DIRECT
  - REJECT
  - "PING"
  - "LB SG"
  - "LB ID"
- name: YouTube
  type: select
  use:
  - "ID"
  - "SG"
  proxies:
  - PRANA
  - DIRECT
  - REJECT
  - "PING"
  - "LB SG"
  - "LB ID"
- name: Speedtest
  type: select
  use:
  - "ID"
  - "SG"
  proxies:
  - PRANA
  - DIRECT
  - REJECT
  - "PING"
  - "LB SG"
  - "LB ID"
- name: ADS
  type: select
  disable-udp: false
  use:
  - "ID"
  - "SG"
  proxies:
  - PRANA
  - DIRECT
  - REJECT
  - "PING"
  - "LB SG"
  - "LB ID"
- name: 18+
  type: select
  disable-udp: false
  use:
  - "ID"
  - "SG"
  proxies:
  - PRANA
  - DIRECT
  - REJECT
  - "PING"
  - "LB SG"
  - "LB ID"
shortcuts:
  TCPgames: network == 'tcp' and dst_port not in [21, 22, 23, 53, 80, 123, 143, 194,
    443, 465, 587, 853, 993, 995, 998, 2052, 2053, 2082, 2083, 2086, 2095, 2096, 5222,
    5228, 5229, 5230, 8080, 8443, 8880, 8883, 8888, 8889]
  UDPgames: network == 'udp' and dst_port not in [21, 22, 23, 53, 80, 123, 143, 194,
    443, 465, 587, 853, 993, 995, 998, 2052, 2053, 2082, 2083, 2086, 2095, 2096, 5222,
    5228, 5229, 5230, 8080, 8443, 8880, 8883, 8888, 8889]
  Speedtest: network == "tcp" and match_provider("rule_Speedtest")
rules:
- DST-PORT,22,DIRECT
- DST-PORT,7895,REJECT
- DST-PORT,7892,REJECT
- RULE-SET,Instagram,Instagram
- RULE-SET,Facebook,Facebook
- RULE-SET,Twitter,Twitter
- RULE-SET,Whatsapp,Whatsapp
- RULE-SET,YouTube,YouTube
- RULE-SET,Speedtest,Speedtest
- RULE-SET,Telegram,Telegram
- RULE-SET,18+,18+
- RULE-SET,ADS,ADS
- RULE-SET,Direct,DIRECT
- SRC-IP-CIDR,192.168.17.1/24,DIRECT
- MATCH,GLOBAL
