# port: 9494
# socks-port: 9595
# mixed-port: 9696
redir-port: 9797
tproxy-port: 9898
mode: rule
allow-lan: true
unified-delay: true
bind-address: '*'
log-level: silent
ipv6: true
geodata-mode: true
geodata-loader: memconservative
external-controller: 0.0.0.0:9090
external-ui: ./dashboard/dist
# secret: ""
tcp-concurrent: false
enable-process: false
inbound-tfo: false
# interface-name: ""
# routing-mark: 233
# geox-url: {
  # mmdb: "",
  # geoip: "",
  # geosite: ""
# }
profile:
  store-selected: true
  store-fake-ip: false
experimental:
  sniff-tls-sni: true
  # fingerprint: ""
sniffer: # sniff domain name optional configuration
  enable: true
  # sniffing protocol required
  sniffing:
    - tls
    - http
  # force sniffing on this domain name
  force-domain:
    - +.v2ex.com
  # Sniff only on ports in the whitelist, default 443, 80
  port-whitelist:
    - 80
    - 443
  # force-dns-mapping: true
  # parse-pure-ip: true
tun:
  enable: false
  # biarkan default utun
  device: utun
  mtu: 9000
  stack: system
  dns-hijack:
    - any:53
  auto-route: false
  auto-detect-interface: false
  # inet4-address: 198.18.0.1/30
  # inet6-address: [fdfe:dcba:9876::1/126]
  strict-route: false
  # inet4-route-address:
    # - 0.0.0.0/1
    # - 128.0.0.0/1
  # inet6-route-address:
    # - '::/1'
    # - '8000::/1'
  # include-android-user:
    # - 0
    # - 10
dns:
  enable: true
  ipv6: true # false akan mengembalikan hasil kosong untuk AAAA
  prefer-h3: false
  default-nameserver:
    - 8.8.8.8
    # - tls://9.9.9.11:853
    - tls://1.0.0.1:853
  listen: 0.0.0.0:1053
  use-hosts: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.local"
    - "*.localhost"
  # proxy-server-nameserver:
    # - '1.0.0.1'
  nameserver:
    - 8.8.8.8 # default value
    - tls://1.1.1.1:853 # DNS over TLS
    # - dhcp://rmnet_data+ # dns from dhcp
    # - https://doh.pub/dns-query # DNS over HTTPS
    # - https://dns.alidns.com/dns-query#h3=true  # Mandatory HTTP/3, irrelevant to perfer-h3, mandatory HTTP/3 support for DoH, if not supported, it will not work
    # - https://mozilla.cloudflare-dns.com/dns-query#DNS&h3=true # Specify policy group and use HTTP/3
    # - quic://dns.adguard.com:784 # DNS over QUIC
    # - '8.8.8.8#en0' # Compatible with designated DNS egress NIC
  # fallback:
    # - 'https://1.0.0.1/dns-query'
    # - 'https://9.9.9.9/dns-query'
  # fallback-filter:
    # geoip: false
    # geoip-code: '!ID'
    # # geosite:
      # # - gfw
    # # ipcidr:
      # # - 240.0.0.0/4
    # domain:
      # - '+.google.com'
      # - '+.facebook.com'
      # - '+.youtube.com'
# hosts: {
  # "ota.googlezip.net": "127.0.0.1",
  # "ota-cache1.googlezip.net": "127.0.0.1",
  # "ota-cache2.googlezip.net": "127.0.0.1"
  # }
proxies:
rule-providers:
  Akrab:
    type: file
    behavior: domain
    url: https://raw.githubusercontent.com/wikann/Rule/main/Direct.yaml
    path: "./rule_provider/Akrab.yaml"
    interval: 100
  Bank:
    type: file
    behavior: domain
    url: https://raw.githubusercontent.com/wikann/Rule/main/Direct.yaml
    path: "./rule_provider/Bank.yaml"
    interval: 100
  ADS:
    type: file
    behavior: domain
    url: https://raw.githubusercontent.com/wikann/Rule/main/Ads.yaml
    path: "./rule_provider/ads.yaml"
    interval: 100
  Instagram:
    type: file
    behavior: domain
    url: https://raw.githubusercontent.com/wikann/Rule/main/Instagram.yaml
    path: "./rule_provider/ig.yaml"
    interval: 100
  Facebook:
    type: file
    behavior: domain
    url: https://raw.githubusercontent.com/wikann/Rule/main/Facebook.yaml
    path: "./rule_provider/fb.yaml"
    interval: 100
  Twitter:
    type: file
    behavior: domain
    url: https://raw.githubusercontent.com/wikann/Rule/main/Twitter.yaml
    path: "./rule_provider/tw.yaml"
    interval: 100
  YouTube:
    type: file
    behavior: domain
    path: "./rule_provider/Youtube.yaml"
    url: https://raw.githubusercontent.com/wikann/Rule/main/Youtube.yaml
    interval: 100
  Speedtest:
    type: file
    behavior: domain
    path: "./rule_provider/Speedtest.yaml"
    url: https://raw.githubusercontent.com/wikann/Rule/main/Speedtest.yaml
    interval: 100
  18+:
    type: file
    behavior: domain
    url: https://raw.githubusercontent.com/wikann/Rule/main/Porn.yaml
    path: "./rule_provider/porn.yaml"
    interval: 100
  Streaming:
    type: file
    behavior: domain
    path: "./rule_provider/streaming.yaml"
    interval: 100
  Telegram:
    type: file
    behavior: domain
    url: https://raw.githubusercontent.com/wikann/Rule/main/Telegram.yaml
    path: "./rule_provider/telegram.yaml"
    interval: 100
proxy-providers:
  "ID":
    type: http
    path: "./confs/ID.yaml"
    url: https://raw.githubusercontent.com/wikann/Akun/main/ID.yaml
    health-check:
      enable: true
      url: http://cp.cloudflare.com/generate_204
      interval: 300
  "SG":
    type: http
    path: "./confs/SG.yaml"
    url: https://raw.githubusercontent.com/wikann/Akun/main/SG.yaml
    health-check:
      enable: true
      url: http://cp.cloudflare.com/generate_204
      interval: 300
proxy-groups:
- name: PRANA
  type: select
  use:
  - "ID"
  - "SG"
  proxies:
  - "PING"
  - "LB ID"
  - "LB SG"
- name: "LB ID"
  type: load-balance
  strategy: round-robin
  disable-udp: false
  use:
  - "ID"
- name: "LB SG"
  type: load-balance
  strategy: round-robin
  disable-udp: false
  use:
  - "SG"
  url: http://www.gstatic.com/generate_204
  interval: '300'
- name: "PING"
  type: url-test
  disable-udp: false
  use:
  - "ID"
  - "SG"
  url: http://cp.cloudflare.com/generate_204
  interval: '300'
  tolerance: '150'
- name: Instagram
  type: select
  use:
  - "ID"
  - "SG"
  proxies:
  - PRANA
  - DIRECT
  - REJECT
  - "PING"
  - "LB SG"
  - "LB ID"
- name: Bank
  type: select
  use:
  - "ID"
  - "SG"
  proxies:
  - PRANA
  - DIRECT
  - REJECT
  - "PING"
  - "LB SG"
  - "LB ID"
- name: Facebook
  type: select
  use:
  - "ID"
  - "SG"
  proxies:
  - PRANA
  - DIRECT
  - REJECT
  - "PING"
  - "LB SG"
  - "LB ID"
- name: Twitter
  type: select
  use:
  - "ID"
  - "SG"
  proxies:
  - PRANA
  - DIRECT
  - REJECT
  - "PING"
  - "LB SG"
  - "LB ID"
- name: Telegram
  type: select
  use:
  - "ID"
  - "SG"
  proxies:
  - PRANA
  - DIRECT
  - REJECT
  - "PING"
  - "LB SG"
  - "LB ID"
- name: YouTube
  type: select
  use:
  - "ID"
  - "SG"
  proxies:
  - PRANA
  - DIRECT
  - REJECT
  - "PING"
  - "LB SG"
  - "LB ID"
- name: Speedtest
  type: select
  use:
  - "ID"
  - "SG"
  proxies:
  - PRANA
  - DIRECT
  - REJECT
  - "PING"
  - "LB SG"
  - "LB ID"
- name: 18+
  type: select
  disable-udp: false
  use:
  - "ID"
  - "SG"
  proxies:
  - PRANA
  - DIRECT
  - REJECT
  - "PING"
  - "LB SG"
  - "LB ID"
shortcuts:
  TCPgames: network == 'tcp' and dst_port not in [21, 22, 23, 53, 80, 123, 143, 194,
    443, 465, 587, 853, 993, 995, 998, 2052, 2053, 2082, 2083, 2086, 2095, 2096, 5222,
    5228, 5229, 5230, 8080, 8443, 8880, 8883, 8888, 8889]
  UDPgames: network == 'udp' and dst_port not in [21, 22, 23, 53, 80, 123, 143, 194,
    443, 465, 587, 853, 993, 995, 998, 2052, 2053, 2082, 2083, 2086, 2095, 2096, 5222,
    5228, 5229, 5230, 8080, 8443, 8880, 8883, 8888, 8889]
  Speedtest: network == "tcp" and match_provider("rule_Speedtest")
rules:
- DST-PORT,22,DIRECT
- DST-PORT,7895,REJECT
- DST-PORT,7892,REJECT
- RULE-SET,Instagram,Instagram
- RULE-SET,Facebook,Facebook
- RULE-SET,Twitter,Twitter
- RULE-SET,YouTube,YouTube
- RULE-SET,Speedtest,Speedtest
- RULE-SET,Telegram,Telegram
- RULE-SET,18+,18+
- RULE-SET,ADS,REJECT
- RULE-SET,Akrab,DIRECT
- RULE-SET,Bank,Bank
- MATCH,GLOBAL
