proxies:
rule-providers:

  Rule_Reject:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AdGuardSDNSFilter/AdGuardSDNSFilter_Classical.yaml
    path: "./rule_provider/reject.yaml"
    interval: 100
  Rule_Instagram:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Instagram/Instagram.yaml
    path: "./rule_provider/ig.yaml"
    interval: 100
  Rule_Facebook:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Facebook/Facebook.yaml
    path: "./rule_provider/fb.yaml"
    interval: 100
 Rule_ Twitter:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitter/Twitter.yaml
    path: "./rule_provider/tw.yaml"
    interval: 100
  Rule_Akrab:
    type: http
    behavior: classical
    url : https://raw.githubusercontent.com/wikann/Rule/main/Akrab.yaml
    path: "./rule_provider/Akrab.yaml"
    interval: 100
  Rule_YouTube:
    type: http
    behavior: classical
    path: "./rule_provider/Youtube.yaml"
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.yaml
    interval: 100
  Rule_Speedtest:
    type: http
    behavior: classical
    path: "./rule_provider/Speedtest.yaml"
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.yaml
    interval: 100
  Rule_18+:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/wikann/Rule/main/porn.yaml
    path: "./rule_provider/porn.yaml"
    interval: 100
  Rule_Netflix:
    type: http
    behavior: classical
    url: https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Netflix/Netflix.yaml
    path: "./rule_provider/Netflix.yaml"
    interval: 100
  Rule_TikTok:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.yaml
    path: "./rule_provider/TikTok.yaml"
    interval: 100
  Rule_Shopee:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Shopee/Shopee.yaml
    path: "./rule_provider/Shopee.yaml"
    interval: 100
  Rule_Bank:
    type: http
    behavior: classical
    url: https:https://raw.githubusercontent.com/wikann/Rule/main/bank.yaml
    path: "./rule_provider/Bank.yaml"
    interval: 100
  Rule_Telegram:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.yaml
    path: "./rule_provider/telegram.yaml"
    interval: 100
proxy-providers:
  "ID":
    type: http
    path: "./confs/ID.yaml"
    url: https://raw.githubusercontent.com/wikann/Akun/main/ID.yaml?token=GHSAT0AAAAAAB45QQI54T7CTPPYAUWTXBOOY5QX2AA
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  "SG":
    type: http
    path: "./confs/SG.yaml"
    url: https://raw.githubusercontent.com/wikann/Akun/main/SG.yaml?token=GHSAT0AAAAAAB45QQI4YNSIT3UINGQPYKE2Y5QX2OA
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
proxy-groups:
- name: PRANA
  type: select
  use:
  - "ID"
  - "SG"
  proxies:
  - "PING"
  - "LB ID"
  - "LB SG"
- name: "LB ID"
  type: load-balance
  strategy: round-robin
  disable-udp: false
  use:
  - "ID"
- name: "LB SG"
  type: load-balance
  strategy: round-robin
  disable-udp: false
  use:
  - "SG"
  url: http://www.gstatic.com/generate_204
  interval: '300'
- name: "PING"
  type: url-test
  disable-udp: false
  use:
  - "ID"
  - "SG"
  url: http://www.gstatic.com/generate_204
  interval: '300'
  tolerance: '150'
- name: Instagram
  type: select
  use:
  - "ID"
  - "SG"
  proxies:
  - PRANA
  - DIRECT
  - REJECT
  - "PING"
  - "LB SG"
  - "LB ID"
- name: TikTok
  type: select
  use:
  - "ID"
  - "SG"
  proxies:
  - PRANA
  - DIRECT
  - REJECT
  - "PING"
  - "LB SG"
  - "LB ID"
- name: Facebook
  type: select
  use:
  - "ID"
  - "SG"
  proxies:
  - PRANA
  - DIRECT
  - REJECT
  - "PING"
  - "LB SG"
  - "LB ID"
- name: Twitter
  type: select
  use:
  - "ID"
  - "SG"
  proxies:
  - PRANA
  - DIRECT
  - REJECT
  - "PING"
  - "LB SG"
  - "LB ID"
- name: Telegram
  type: select
  use:
  - "ID"
  - "SG"
  proxies:
  - PRANA
  - DIRECT
  - REJECT
  - "PING"
  - "LB SG"
  - "LB ID"
- name: YouTube
  type: select
  use:
  - "ID"
  - "SG"
  proxies:
  - PRANA
  - DIRECT
  - REJECT
  - "PING"
  - "LB SG"
  - "LB ID"
- name: Speedtest
  type: select
  use:
  - "ID"
  - "SG"
  proxies:
  - PRANA
  - DIRECT
  - REJECT
  - "PING"
  - "LB SG"
  - "LB ID"
- name: Bank
  type: select
  use:
  - "ID"
  - "SG"
  proxies:
  - PRANA
  - DIRECT
  - REJECT
  - "PING"
  - "LB SG"
  - "LB ID"
- name: Streaming
  type: select
  disable-udp: false
  use:
  - "ID"
  - "SG"
  proxies:
  - PRANA
  - DIRECT
  - REJECT
  - "PING"
  - "LB SG"
  - "LB ID"
- name: 18+
  type: select
  disable-udp: false
  use:
  - "ID"
  - "SG"
  proxies:
  - PRANA
  - DIRECT
  - REJECT
  - "PING"
  - "LB SG"
  - "LB ID"
shortcuts:
  TCPgames: network == 'tcp' and dst_port not in [21, 22, 23, 53, 80, 123, 143, 194,
    443, 465, 587, 853, 993, 995, 998, 2052, 2053, 2082, 2083, 2086, 2095, 2096, 5222,
    5228, 5229, 5230, 8080, 8443, 8880, 8883, 8888, 8889]
  UDPgames: network == 'udp' and dst_port not in [21, 22, 23, 53, 80, 123, 143, 194,
    443, 465, 587, 853, 993, 995, 998, 2052, 2053, 2082, 2083, 2086, 2095, 2096, 5222,
    5228, 5229, 5230, 8080, 8443, 8880, 8883, 8888, 8889]
  Speedtest: network == "tcp" and match_provider("rule_Speedtest")
rules:
- RULE-SET,Rule_Reject,REJECT
- RULE-SET,Rule_Instagram,Instagram
- RULE-SET,Rule_Facebook,Facebook
- RULE-SET,Rule_Twitter,Twitter
- RULE-SET,Rule_Akrab,DIRECT
- RULE-SET,Rule_YouTube,YouTube
- RULE-SET,Rule_Speedtest,Speedtest
- RULE-SET,Rule_18+,18+
- RULE-SET,Rule_Netflix,Streaming
- RULE-SET,Rule_TikTok,TikTok
- RULE-SET,Rule_Bank,Bank
- RULE-SET,Rule_Shopee,Bank
- RULE-SET,Rule_Telegram,Telegram
- MATCH,GLOBAL








